### ISSUE TITLE
0015 - Contact page button does nothing

### ISSUE THREAD

**Issue by regalcat** [ISU-WebDevClub/club-website#33]
Make the contact page button send an email to the club or at least the officers.

**Comment by KrashLeviathan** [comment]
Short term solution: I think we should just remove it for now until we can fully implement a secure mail form with capcha or something. I'd rather have NO contact page than have one that doesn't work. We have the mailto link in the footer, so that could be good for now until we spin something better up in the future.

**Comment by frostbyte100** [comment]
I'll complete this during winter break.

**Comment by KrashLeviathan** [comment]
Sounds good. In the meantime I'm just going to remove links to the contact page so nobody tries to use the broken form.

**Comment by KrashLeviathan** [comment]
...eh, rather than removing the link to the page, I just commented out the form and wrote something in its place. @frostbyte100 over break if you want to tackle fully implementing that form, that would be great. I think @regalcat mentioned there were security vulnerabilities in using a form, so you'll have to look into that when you work on it.

**Comment by frostbyte100** [comment]
Ok, I believe I have fixed it. Just to confirm. The website is now hosted on some server that the Iowa State I.T. department runs right? Because my solution only works if it is.

**Comment by KrashLeviathan** [comment]
@frostbyte100 was this one still waiting to get merged or was it complete? Just wondering if I should re-create the Issue on the new repo.

**Comment by frostbyte100** [comment]
It was waiting to be merged

On Thu, Feb 25, 2016 at 3:57 PM, Nathan Karasch <notifications@github.com>
wrote:

> @frostbyte100 <https://github.com/frostbyte100> was this one still
> waiting to get merged or was it complete? Just wondering if I should
> re-create the Issue on the new repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ISU-WebDevClub/club-website/issues/33#issuecomment-189004286>
> .
>



-- 
Leelabari Fulbel

**Comment by frostbyte100** [comment]
I'll email Levi on Monday morning to ask him to repull all of the changes on the repo to the server so we can test out the button but hopefully it should work.

**Comment by frostbyte100** [comment]
This works now!
